<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.avispl.symphony.tal</groupId>
  <artifactId>symphony-tal-connectwise</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>11</source>
          <target>11</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <packaging>jar</packaging>

  <name>symphony-tal-sample</name>
  <description>Sample Symphony Ticket Adapter</description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <java.version>1.8</java.version>
    <org.json.version>20240303</org.json.version>
    <logback-classic.version>1.5.13</logback-classic.version>
    <org.springframework.boot.version>3.4.1</org.springframework.boot.version>
    <spring-context.verison>6.2.1</spring-context.verison>
    <org.junit.jupiter.version>5.10.2</org.junit.jupiter.version>
    <org.mockito.version>5.12.0</org.mockito.version>
    <com.fasterxml.jackson.core.version>2.17.1</com.fasterxml.jackson.core.version>
    <!--- Symphony Dependencies -->
    <symphony-bom.version>6.4.0.2410211539</symphony-bom.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>${org.json.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>${org.springframework.boot.version}</version>
    </dependency>
    <dependency>
      <artifactId>logback-classic</artifactId>
      <groupId>ch.qos.logback</groupId>
      <version>${logback-classic.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <version>${org.springframework.boot.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>${spring-context.verison}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-autoconfigure</artifactId>
      <version>${org.springframework.boot.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${org.junit.jupiter.version}</version>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>${org.mockito.version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${com.fasterxml.jackson.core.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
      <version>4.4</version>
    </dependency>
    <!--- Symphony Dependencies -->
    <dependency>
      <groupId>com.avispl.symphony.api</groupId>
      <artifactId>symphony-api-tal</artifactId>
    </dependency>
    <dependency>
      <groupId>com.avispl.symphony.api</groupId>
      <artifactId>symphony-api-commons</artifactId>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.avispl.symphony</groupId>
        <artifactId>symphony-bom</artifactId>
        <version>${symphony-bom.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <distributionManagement>
    <repository>
      <id>avi-spl.releases</id>
      <url>https://nexus.vnocsymphony.com:8443/repository/maven-releases/</url>
    </repository>
    <snapshotRepository>
      <id>avi-spl.snapshots</id>
      <url>https://nexus.vnocsymphony.com:8443/repository/maven-snapshots/</url>
    </snapshotRepository>
  </distributionManagement>
  <repositories>
    <repository>
      <id>avi-spl.releases</id>
      <url>https://nexus.vnocsymphony.com:8443/repository/maven-releases/</url>
    </repository>
    <repository>
      <id>avi-spl.snapshots</id>
      <url>https://nexus.vnocsymphony.com:8443/repository/maven-snapshots/</url>
    </repository>
  </repositories>
</project>
